apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-config
data:
  db_password: {{ default "" .Values.db_password | b64enc }}
  db_username: {{ default "" .Values.db_username | b64enc }}
  db_host: {{ default "" .Values.db_host | b64enc }}
  db_name: {{ default "" .Values.db_name | b64enc }}
  webhook_url: {{ default "" .Values.webhook_url | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-docker-cred
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}


